Specialize templates to get fully qualified name
aica-technology/modulo pull request #35
Opened 2023-06-13 08:30 UTC by domire8

## Description

- #27 

`get_fully_qualified_name()` is not correct for the lifecycle component, so this needs specialization until we refactor the component interface.

## Review guidelines

Estimated Time of Review: 2 minutes

2023-06-13 17:43 UTC, eeberhard requested changes
NOT YET

2023-06-13 17:47 UTC, domire8 commented on source/modulo_components/include/modulo_components/ComponentInterface.hpp
>  template<class NodeT>
```suggestion
template<class NodeT>
```

2023-06-13 17:47 UTC, domire8 commented on source/modulo_components/include/modulo_components/ComponentInterface.hpp
>    message.component = this->get_fully_qualified_name();
```suggestion
template<typename NodeT>
inline void ComponentInterface<NodeT>::publish_predicate(const std::string& name) {
  modulo_component_interfaces::msg::Predicate message;
  message.component = this->get_node_base_interface()->get_fully_qualified_name();
```

2023-06-13 17:50 UTC, eeberhard approved these changes

2023-06-13 18:54 UTC, domire8 commented
I think this is now what you were looking for. The name of the predicate is `/<namespace>/<node_name>` or just `/<node_name>` like that (tested)

2023-06-26 07:20 UTC, eeberhard approved these changes

2023-06-26 07:28 UTC, merged